ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PARTICIPANT_KICKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PARTICIPANT_CHECKIN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PARTICIPANT_UNDO_CHECKIN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHEDULE_UPDATED';

ALTER TABLE "user_profiles"
ALTER COLUMN "first_name" DROP NOT NULL,
ALTER COLUMN "last_name" DROP NOT NULL;

ALTER TABLE "hackathons"
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "registration_start" DROP NOT NULL,
ALTER COLUMN "registration_end" DROP NOT NULL,
ALTER COLUMN "event_start" DROP NOT NULL,
ALTER COLUMN "event_end" DROP NOT NULL,
ALTER COLUMN "submission_deadline" DROP NOT NULL;
